# Load defaults
. ../defaults.ps1

# Selects the packer variables file: variables-$BASE.pkrvars.hcl
# (CPU/RAM/disk, credentials — ISO values are overridden below)
$BASE        = "winfor"

# Packer config directory and template file to build: $CONF_NAME/$CONF_NAME.pkr.hcl
$CONF_NAME   = "winfor"

# Output folder name used by VMware and when moving the VM to $VM_DIR
$VM_DIR_NAME = "WIN-FOR"

# Fetch (or reuse cached) Windows 11 ISO from the Microsoft Evaluation Center.
# Resolves the fwlink redirect at runtime — no hardcoded URL to maintain.
# The ISO is stored in packer-windows\iso\ and excluded from git.
$iso = & "$PSScriptRoot\fetch-win-iso.ps1"

# Write a temporary var file that overrides the ISO placeholders in
# variables-winfor.pkrvars.hcl with the actual local path and checksum.
# The file is cleaned up after the build (try/finally below).
$isoFileUrl = "file:///" + $iso.Path.Replace('\', '/')
$isoVarFile = "$PSScriptRoot\variables-winfor-iso.pkrvars.hcl"
@"
// Auto-generated by build-winfor.ps1 — do not edit, it is deleted after the build
iso_urls_windows     = ["$isoFileUrl"]
iso_checksum_windows = "$($iso.Checksum)"
"@ | Set-Content -Path $isoVarFile -Encoding utf8

try {
    # Pass the generated var file as an override; packer applies it after
    # variables-winfor.pkrvars.hcl so the ISO placeholders are replaced.
    New-VirtualMachine $BASE $CONF_NAME $VM_DIR_NAME -ExtraVarFiles @("../variables-winfor-iso.pkrvars.hcl")
} finally {
    Remove-Item -Path $isoVarFile -ErrorAction SilentlyContinue
}
